# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number
    
create_formation:
    path: /create/formation
    controller: App\Controller\FormationController::create
    
create_experience:
    path: /create/experience
    controller: App\Controller\ExperienceController::create
    
create_loisir:
    path: /create/loisir
    controller: App\Controller\LoisirController::create

valid_formation:
    path: /valid/formation
    controller: App\Controller\FormationController::valid

valid_experience:
    path: /valid/experience
    controller: App\Controller\ExperienceController::valid
    
valid_loisir:
    path: /valid/loisir
    controller: App\Controller\LoisirController::valid
    
edit_formation:
    path: /edit/formation/{id}
    controller: App\Controller\FormationController::edit

edit_experience:
    path: /edit/experience/{id}
    controller: App\Controller\ExperienceController::edit

edit_loisir:
    path: /edit/loisir/{id}
    controller: App\Controller\LoisirController::edit
    
remove_formation:
    path: /remove/formation/{id}
    controller: App\Controller\FormationController::remove
    
remove_experience:
    path: /remove/experience/{id}
    controller: App\Controller\ExperienceController::remove
    
remove_loisir:
    path: /remove/loisir/{id}
    controller: App\Controller\LoisirController::remove